data["Objects"] = {
	_visualisation:{
		layout:"Grid"
	},
	bed:{
		_visualisation:{
			layout:"Grid"
		},
		homeBed:{
			_visualisation:{
				shortname:"Double Bed",
				manufacturer:"Ikea",
				brand:"HEMNES",
			},
			type:"Objects/bed",
			example:"ObjectExamples/beds/doubleBed",
			resources:{
				space:{
					name:"Space m^2",
					quantity:4 //can take at most 4 people in it at once
				},
			},
			properties:
			{
				location:"Locations/bedroom/homeBedroom/objects/default",
			},
			agents:{
				default:[],
			},
			objects:{
				default:[],
				under:[],
			},
		},
	},
	sofa:{
		_visualisation:{
			layout:"Grid"
		},
		homeSofa:{
			_visualisation:{
				shortname:"Sofa",
				manufacturer:"Ikea",
				brand:"LANDSKRONA",
			},
			type:"Objects/sofa",
			example:"ObjectExamples/chairs/sofa",
			resources:{
				space:{
					name:"Space m^2",
					quantity:2 //can take at most 2 people in it at once
				},
			},
			properties:
			{
				location:"Locations/livingroom/homeLivingroom/objects/default",
			},
			agents:{
				default:[],
			},
			objects:{
				default:[],
				under:[],
			},
		},
	},
	deskChair:{
		_visualisation:{
			layout:"Grid"
		},
		homeChair:{
			_visualisation:{
				shortname:"Desk Chair",
				manufacturer:"Ikea",
				brand:"FLINTAN",
			},
			type:"Objects/deskChair",
			example:"ObjectExamples/chairs/deskChair",
			resources:{
				space:{
					name:"Space m^2",
					quantity:1
				},
			},
			properties:
			{
				location:"Locations/livingroom/homeLivingroom/objects/default",
			},
			agents:{
				default:[],
			},
			objects:{
				default:[],
			},
		},
	},
	table:{
		_visualisation:{
			layout:"Grid"
		},
		homeDesk:{
			_visualisation:{
				shortname:"Desk",
				manufacturer:"Ikea",
				brand:"BEKANT",
			},
			type:"Objects/table",
			example:"ObjectExamples/tables/desk",
			resources:{
				space:{
					name:"Space m^2",
					quantity:2
				},
			},					
			properties:
			{
				location:"Locations/livingroom/homeLivingroom/objects/default",
			},
			agents:{
				default:[],
			},
			objects:{
				default:[],
				under:[],
			},
		},
	},
	debitCard:{
		_visualisation:{
			shortname:"Debit Cards"
		},
		"0123 0123 0123 0123":{
			_visualisation:{
				shortname:"Visa Debit Card",
				manufacturer:"Halifax",
				brand:"Visa Debit",
			},
			type:"Objects/debitCard",
			example:"ObjectExamples/cards/debitCard",
			resources:{
			},					
			properties:
			{
				accountCard:"DataStorages/bankAccounts/halifax/properties/accounts/jackBurton/currentAccounts/account0/cards/0123 0123 0123 0123",
				location:"Agent/player/me/objects/default",
			},
		},
	},
	cheque:{
		_visualisation:{
			shortname:"Cheques"
		},
		unemploymentCheque:{
			_visualisation:{
				shortname:"JobSeekers Allowance Cheque",
				manufacturer:"Halifax",
				brand:"Cheque",
			},
			type:"Objects/cheque",
			example:"ObjectExamples/cheques/cheque",
			resources:{
			},					
			properties:
			{
				fromAccount:"DataStorages/bankAccounts/ukGovernmentInternal/properties/accounts/VAT/businessAccounts/account0",
				toPerson:"Agents/player/me",
				quantity:59.20,
				location:"Agent/player/me/objects/default",
			},
		},
	},
	cardboardBox:{
	},
	chewits:{
	},
	chewit:{
	},
	chewitWrapper:{
	},
};